services:
  backend:
    build: ./server
    container_name: mentor-backend
    ports:
      - "5000:5000"
    environment:
      - MONGO_URI=${MONGO_URI}
      - PORT=5000

  frontend:
    build: ./client
    container_name: mentor-frontend
    ports:
      - "3000:80"
    depends_on:
      - backend
